### ISSUE TITLE
您好，求助！

### ISSUE THREAD

**Issue by peaky2222** [qiuxy23/DC-DRL#1]
您好，最近看了您的论文，对您的实验十分感兴趣但是再复现实验的过程中遇到了一些问题，可以将您的源代码发送一份给我吗？邮箱：peakyu2020@163.com,不盛感激，github上的代码缺失的部分较多，我在复现时有较多的问题导致无法实现。望您看到后回复，谢谢！

**Comment by LittleFish33** [comment]
您好，请问能提供具体的报错信息吗？github上的代码应该根据想要复现的实验提供对应的参数就可以跑起来的

**Comment by qiuxy23** [comment]
您好，请问是否能提供报错信息，应该根据要复现的实验提供对应的参数就能跑了

**Comment by peaky2222** [comment]
> 您好，请问是否能提供报错信息，应该根据要复现的实验提供对应的参数就能跑了

是的，对于您的‘MyENV-10’的信息，缺少这个环境所以无法进行与环境交互，我猜测。谢谢

**Comment by qiuxy23** [comment]
代码应该已经提供了环境，我怀疑有可能是有个地方被改了，然后当做gym环境处理了，因为如果不是gym环境，直接载入是没问题的

**Comment by peaky2222** [comment]
那您的源代码能我能调试学习一下吗？如上可以发送到我的邮箱，谢谢您peakyu2020@163.com，十分感谢

**Comment by syue0225** [comment]
作者您好，特别欣赏您的论文，但是在执行过程中出现如下错误，未找到解决方案，可以帮帮忙吗？非常感谢  File "E:\python_code\03DC-DRL-master\DC-DRL-master\common_modules\env_utils.py", line 13, in init_pos
    return np.random.randint(low=-(cover_range), high=cover_range, size=n_users * 2)
**TypeError: bad operand type for unary -: 'NoneType'**

**Comment by syue0225** [comment]
而且**缺少很多.npy文件**，FileNotFoundError: [Errno 2] No such file or directory: 'exps/exp_1_1_10000.npy'，您可以帮帮我吗

**Comment by wail-asad** [comment]
@qiuxy23 
**In the readme** "* client.py: deploy on the client side, which is responsible to interacting with env. and collect experience, multiple clients can provide higher diversity"
but I didn't find client.py file outside the "testbad" directory.
I want to understand how the client side trains the NN model and share the experience.
with a lot of thanks

**Comment by milkybearone** [comment]
> MyENV-10

您好，可以给我发一份么，我跑的时候也出了对应的问题
